add v1/auth/user/reset POST spec
mai-806/Delivery.Backend pull request #26
Opened 2023-07-03 19:59 UTC by AntonCkya

2023-07-03 20:47 UTC, Yeloki requested changes

2023-07-03 20:47 UTC, Yeloki commented on deli-auth/docs/api.yaml
> +        newPassword:
Давай также пароль в хидере передавать? И сделай пж 4 пробела вместо 2 - так ямл файл читабельнее станет

2023-07-04 10:27 UTC, RoKivals commented on deli-auth/docs/api.yaml
> +            parameters:
Добавь required для обоих параметров

2023-07-04 10:27 UTC, RoKivals commented on deli-auth/docs/api.yaml
> +                '204':
Сюда можно title (OK) ещё впихнуть, это даже полезнее description будет

2023-07-04 11:19 UTC, RoKivals commented on deli-auth/docs/api.yaml
> +                '204':
Я прописал, что 204 response не имеет тела, следовательно в него нельзя запихнуть content. А попросил я просто добавить title и всё. Из компонентов тело 204 тоже надо удалить в таком случае.

По документации 204 response является no content)

2023-07-04 12:09 UTC, RoKivals approved these changes

2023-07-04 12:12 UTC, RoKivals approved these changes

2023-07-04 12:13 UTC, merged